name: Generate Directory Listing

on:
  push:
    branches:
      - main  # Change this if your branch is not "main"

jobs:
  generate-listing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Generate Directory Listings
        uses: jayanta525/github-pages-directory-listing@v4.0.0
        with:
          FOLDER: fonts  # Change this to the directory you want to list

      - name: Commit and Push Changes
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}.git
          git add fonts/index.html
          git commit -m "Auto-generate directory listing"
          git push origin main
